/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo.pitest;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
