/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    compileOnly ("org.projectlombok:lombok:1.18.28")
    annotationProcessor("org.projectlombok:lombok:1.18.28")

    testImplementation("org.mockito:mockito-junit-jupiter:5.4.0")
    testImplementation("org.assertj:assertj-core:3.24.2")
}

application {
    // Define the main class for the application.
    mainClass.set("pitest.gh.app.App")
}
