name: 'pitest'
jobs:
  pitest-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean
      - name: Log
        working-directory: .
        run: |
            ls -la
        shell: bash
#      - name: Upload report
#        uses: actions/upload-artifact@v2
#        with:
#          name: reports-artifact
#          path: ads-campaigns-manager-api/build/reports/pitest/mutations.xml # ${{ inputs.reports-path }}
#          retention-days: 1 # ${{ inputs.reports-retention }}
#      - name: Comment
#        uses: mshick/add-pr-comment@v1
#        with:
#          message: |
#            🧟‍♀ Mutation Testing Summary ️🧟‍♀️
#            ================================
#            *Check artifacts for the complete report*
#          repo-token: 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 # ${{ inputs.repo-token }}
#          repo-token-user-login: 'github-actions[bot]'
#          allow-repeats: true

