# https://github.com/isamadrid90/gradle-pitest-comment-action/blob/main/action.yml
name: 'pitest'
on: [pull_request]
jobs:
  pitest-report:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run build with Gradle Wrapper
        run: |
          echo 'Executing pitest'
          GRADLE_OUTPUT=$(./gradlew pitest 2>&1) || true
          echo "gradle output: $GRADLE_OUTPUT"
          FROM_MUTATION_RESULTS=${GRADLE_OUTPUT##*=}
          echo "From mutation: $FROM_MUTATION_RESULTS"
          MUTATION_RESULTS="${FROM_MUTATION_RESULTS%%per mutation)*}per mutation)"
          echo "Mutation Results: $MUTATION_RESULTS"
          echo 'summary_mutation<<EOF' >> $GITHUB_ENV
          echo $MUTATION_RESULTS | sed 's/>> /\n - /g' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "summary_mutation=${{ env.summary_mutation }}"
#      - name: Upload report
#        uses: actions/upload-artifact@v2
#        with:
#          name: reports-artifact
#          path: ads-campaigns-manager-api/build/reports/pitest/mutations.xml # ${{ inputs.reports-path }}
#          retention-days: 1 # ${{ inputs.reports-retention }}
      - name: Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            🧟 Mutation Testing Summary ️🧟
            ================================
            ${{ env.summary_mutation }}
            *Check artifacts for the complete report*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true

